/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.util.List;
import model.GerenciadorFinanceiro;
import model.Despesa;

/**
 *
 * @author Usuário
 */
public class TelaListaDespesas extends javax.swing.JDialog {

    /**
     * Creates new form TelaListaDespesas
     */
    public TelaListaDespesas(java.awt.Frame parent, boolean modal, GerenciadorFinanceiro gerenciador) {
        initComponents();
        StringBuilder lista = new StringBuilder();

        List<Despesa> despesas = gerenciador.getDespesas();
        for (Despesa despesa : despesas) {
            lista.append(despesa.toString());
        }
        taListaDespesas.setText(lista.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taListaDespesas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        taListaDespesas.setColumns(20);
        taListaDespesas.setRows(5);
        jScrollPane1.setViewportView(taListaDespesas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taListaDespesas;
    // End of variables declaration//GEN-END:variables
}
