/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.io.IOException;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ArquivoCSV;
import model.Despesa;
import model.GerenciadorFinanceiro;

/**
 *
 * @author Usuário
 */
public class TelaIncluirDespesas extends javax.swing.JDialog {

    private GerenciadorFinanceiro gerenciador;
    
    /**
     * Creates new form TelaIncluirDespesas
     * @param parent
     * @param modal
     * @param gerenciador
     */
    public TelaIncluirDespesas(java.awt.Frame parent, boolean modal, GerenciadorFinanceiro gerenciador) {
        this.gerenciador = gerenciador;
        initComponents();
        MaskFormatter dateMask = null;
        try {
            dateMask = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(TelaIncluirDespesas.class.getName()).log(Level.SEVERE, null, ex);
        }
        dateMask.setPlaceholderCharacter('_');
        tfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(dateMask));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        rbAlimentacao = new javax.swing.JRadioButton();
        rbTransporte = new javax.swing.JRadioButton();
        rbFerias = new javax.swing.JRadioButton();
        rbOutro = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tfData = new javax.swing.JFormattedTextField();
        btAdicionar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Descrição: ");

        buttonGroup1.add(rbAlimentacao);
        rbAlimentacao.setSelected(true);
        rbAlimentacao.setText("Alimentação");
        rbAlimentacao.setActionCommand("ALIMENTACAO");

        buttonGroup1.add(rbTransporte);
        rbTransporte.setText("Transporte");
        rbTransporte.setActionCommand("TRANSPORTE");

        buttonGroup1.add(rbFerias);
        rbFerias.setText("Residência");
        rbFerias.setActionCommand("RESIDENCIA");

        buttonGroup1.add(rbOutro);
        rbOutro.setText("Saúde");
        rbOutro.setActionCommand("SAUDE");

        jLabel2.setText("Data: ");

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Educação");
        jRadioButton1.setActionCommand("EDUCACAO");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Entretenimento");
        jRadioButton2.setActionCommand("ENTRETENIMENTO");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Outro");
        jRadioButton3.setActionCommand("OUTRO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfData))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(btAdicionar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btFechar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfValor)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbAlimentacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbTransporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFerias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbOutro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAlimentacao)
                    .addComponent(rbTransporte)
                    .addComponent(rbFerias)
                    .addComponent(rbOutro)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btFechar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        String descricao = tfDescricao.getText();
        double valorDespesa = 0;
        LocalDate data;
        if (descricao.isBlank()) {
            JOptionPane.showMessageDialog(this, "ERRO: Preencha o campo descrição");
            return;
        }
        
        try {
            if (tfValor.getText().isBlank())
                throw new Exception();

            valorDespesa = Double.parseDouble(tfValor.getText());
            if(valorDespesa<=0)
                throw new Exception();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERRO: Campo Valor não está correto");
            return;
        }
        
        String tipoDespesa = buttonGroup1.getSelection().getActionCommand();
        
        String dataStr = tfData.getText();
        
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            data = LocalDate.parse(dataStr, formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "ERRO: Campo data está incorreto. Preencha no formato dia/mês/ano");
            return;
        }
        
        Despesa despesa = new Despesa(descricao, valorDespesa, data, Despesa.CategoriaDespesa.valueOf(tipoDespesa));
        gerenciador.adicionarDespesa(despesa);
        try {
            ArquivoCSV.salvarDespesa("src\\model\\despesas.csv", gerenciador.getDespesas());
        } catch (IOException ex) {
            Logger.getLogger(TelaIncluirDespesas.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btAdicionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btFechar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton rbAlimentacao;
    private javax.swing.JRadioButton rbFerias;
    private javax.swing.JRadioButton rbOutro;
    private javax.swing.JRadioButton rbTransporte;
    private javax.swing.JFormattedTextField tfData;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
