/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Exercicio1;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JTextArea;
import java.util.Comparator;

/**
 *
 * @author artri
 */
public class TelaRelatorio extends javax.swing.JDialog {

    private Turma turma;

    public TelaRelatorio(java.awt.Frame parent, boolean modal, Turma turma) {
        super(parent, modal);
        this.turma = turma;
        initComponents();
        preencherRelatorio();
    }

    public void preencherRelatorio() {
        StringBuilder texto = new StringBuilder();
        if (turma != null) {

            texto.append("Disciplina: ").append(turma.getDisciplina()).append("\n");
            texto.append("Turno: ").append(turma.getTurno()).append("\n");
            texto.append("------------------------------------------------\n");
            texto.append("Professor: ").append(turma.getProfessor().getNome()).append("\n");
            texto.append("E-mail: ").append(turma.getProfessor().getEmail()).append("\n");
            texto.append("Titulação: ").append(turma.getProfessor().getTitulacao()).append("\n");
            texto.append("Alunos:\n");

            for (Aluno aluno : turma.getAlunos()) {
                texto.append(aluno.getNome())
                        .append(" - ").append(aluno.getMatricula()).append(" - Nota ENEM: ")
                        .append(aluno.getNotaEnem()).append("\n");
            }

            taRelatorio.setText(texto.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRelatorio = new javax.swing.JTextArea();
        btFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbNome = new javax.swing.JRadioButton();
        rbMatricula = new javax.swing.JRadioButton();
        rbNota = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbCrescente = new javax.swing.JRadioButton();
        rbDecrescente = new javax.swing.JRadioButton();
        btListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        taRelatorio.setEditable(false);
        taRelatorio.setColumns(20);
        taRelatorio.setRows(5);
        jScrollPane1.setViewportView(taRelatorio);

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        jLabel1.setText("Ordenar Por:");

        buttonGroup1.add(rbNome);
        rbNome.setSelected(true);
        rbNome.setText("Nome");

        buttonGroup1.add(rbMatricula);
        rbMatricula.setText("Matrícula");

        buttonGroup1.add(rbNota);
        rbNota.setText("Nota Enem");

        jLabel2.setText("Ordem:");

        buttonGroup2.add(rbCrescente);
        rbCrescente.setSelected(true);
        rbCrescente.setText("Crescente");

        buttonGroup2.add(rbDecrescente);
        rbDecrescente.setText("Decrescente");

        btListar.setText("Listar");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbCrescente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbDecrescente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbMatricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbNota)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(btListar)
                        .addGap(18, 18, 18)
                        .addComponent(btFechar)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rbNome)
                            .addComponent(rbMatricula)
                            .addComponent(rbNota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rbCrescente)
                            .addComponent(rbDecrescente))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btFechar)
                            .addComponent(btListar))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        //Nome
        if(rbNome.isSelected()){
        taRelatorio.setText("");
        StringBuilder texto = new StringBuilder();

        texto.append("Disciplina: ").append(turma.getDisciplina()).append("\n");
        texto.append("Turno: ").append(turma.getTurno()).append("\n");
        texto.append("------------------------------------------------\n");
        texto.append("Professor: ").append(turma.getProfessor().getNome()).append("\n");
        texto.append("E-mail: ").append(turma.getProfessor().getEmail()).append("\n");
        texto.append("Titulação: ").append(turma.getProfessor().getTitulacao()).append("\n");
        texto.append("Alunos:\n");
        
        Collections.sort(turma.getAlunos(), new ComparadorPorNome());
            
        if(rbDecrescente.isSelected())
            Collections.sort(turma.getAlunos(), new ComparadorPorNome().reversed());

        for (Aluno aluno : turma.getAlunos()) {
            texto.append(aluno.getNome())
                    .append(" - ").append(aluno.getMatricula()).append(" - Nota ENEM: ")
                    .append(aluno.getNotaEnem()).append("\n");
        }

        taRelatorio.setText(texto.toString());
        }
        
        //Matricula
        if(rbMatricula.isSelected()){
        taRelatorio.setText("");
        StringBuilder texto = new StringBuilder();

        texto.append("Disciplina: ").append(turma.getDisciplina()).append("\n");
        texto.append("Turno: ").append(turma.getTurno()).append("\n");
        texto.append("------------------------------------------------\n");
        texto.append("Professor: ").append(turma.getProfessor().getNome()).append("\n");
        texto.append("E-mail: ").append(turma.getProfessor().getEmail()).append("\n");
        texto.append("Titulação: ").append(turma.getProfessor().getTitulacao()).append("\n");
        texto.append("Alunos:\n");
        
        Collections.sort(turma.getAlunos(), new ComparadorPorMatricula());
            
        if(rbDecrescente.isSelected())
            Collections.sort(turma.getAlunos(), new ComparadorPorMatricula().reversed());

        for (Aluno aluno : turma.getAlunos()) {
            texto.append(aluno.getNome())
                    .append(" - ").append(aluno.getMatricula()).append(" - Nota ENEM: ")
                    .append(aluno.getNotaEnem()).append("\n");
        }

        taRelatorio.setText(texto.toString());
        }
        
        //Nota
        if(rbNota.isSelected()){
        taRelatorio.setText("");
        StringBuilder texto = new StringBuilder();

        texto.append("Disciplina: ").append(turma.getDisciplina()).append("\n");
        texto.append("Turno: ").append(turma.getTurno()).append("\n");
        texto.append("------------------------------------------------\n");
        texto.append("Professor: ").append(turma.getProfessor().getNome()).append("\n");
        texto.append("E-mail: ").append(turma.getProfessor().getEmail()).append("\n");
        texto.append("Titulação: ").append(turma.getProfessor().getTitulacao()).append("\n");
        texto.append("Alunos:\n");
        
        Collections.sort(turma.getAlunos(), new ComparadorPorNota());
            
        if(rbDecrescente.isSelected())
            Collections.sort(turma.getAlunos(), new ComparadorPorNota().reversed());

        for (Aluno aluno : turma.getAlunos()) {
            texto.append(aluno.getNome())
                    .append(" - ").append(aluno.getMatricula()).append(" - Nota ENEM: ")
                    .append(aluno.getNotaEnem()).append("\n");
        }

        taRelatorio.setText(texto.toString());
        }
    }//GEN-LAST:event_btListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btListar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbCrescente;
    private javax.swing.JRadioButton rbDecrescente;
    private javax.swing.JRadioButton rbMatricula;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JRadioButton rbNota;
    private javax.swing.JTextArea taRelatorio;
    // End of variables declaration//GEN-END:variables
}
